# Generated by Django 3.1.7 on 2021-07-14 13:26

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=40, validators=[django.core.validators.EmailValidator(message='Invalid Email Address')])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=40)),
                ('address_line_1', models.CharField(max_length=40)),
                ('address_line_2', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
            ],
        ),
    ]
