version = 1

exclude_patterns = [
  "bin/**",
  "**/node_modules/",
  "js/**/*.min.js"
]

test_patterns = [
  "tests/**",
  "test_*.py"
]



[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt",
  "Pipfile"
]

[[analyzers]]
name = "javascript"
enabled = true
dependency_file_paths = [
    "watchmen/package.json",
]
