# Generated by Django 3.1.7 on 2021-09-10 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_auto_20210902_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=40, null=True)),
                ('means', models.CharField(choices=[('MPESA', 'Pay Through Mpesa'), ('Paypal', 'Paypal'), ('BANK', 'Pay Through Bank'), ('COD', 'Cash On Delivery')], default='MPESA', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('payment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pay', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_transaction', to='order.order')),
            ],
        ),
    ]
