# Generated by Django 3.1.7 on 2021-06-22 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210622_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
