# Generated by Django 3.1.7 on 2021-06-23 07:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_products_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid3, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('CONFIRMED', 'CONFIRMED'), ('FULFILLED', 'FULFILLED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=60)),
                ('currency', models.CharField(blank=True, default='KES', max_length=20, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_of_order', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
                'ordering': ('date_of_order',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'The quantity cannot go below zero')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(blank=True, default='KES', max_length=30, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_cart', to='inventory.products')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='order.order')),
            ],
            options={
                'verbose_name_plural': 'Cart',
                'ordering': ('-pk',),
            },
        ),
    ]
