# Generated by Django 3.1.7 on 2021-06-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210623_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='net_total',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
