# Generated by Django 3.1.7 on 2021-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210623_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(status=['DRAFT']), fields=('customer',), name='one_user_draft'),
        ),
    ]
