# Generated by Django 3.1.7 on 2021-07-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210712_1920'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='one_user_draft',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(status='DRAFT'), fields=('customer',), name='customer_unique_draft'),
        ),
    ]
