# Generated by Django 3.1.7 on 2021-08-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PLACED', 'PLACED'), ('CONFIRMED', 'CONFIRMED'), ('FULFILLED', 'FULFILLED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=60),
        ),
    ]
