# Generated by Django 3.1.7 on 2021-09-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210815_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date_of_order',), 'verbose_name_plural': 'Order'},
        ),
    ]
