name: Django Tests CI Workflow

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # postgres:
  #   container:
  #     image: postgres:12

  flake8:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  pytest:
    runs_on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Install pytest
        run: |
          pip install pytest

      - name: Test with pytest
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: prime
          POSTGRES_PASSWORD: belindat2014
          POSTGRES_NAME: watchmen
          POSTGRES_PORT: 5432
        run: |
          docker-compose -f local.yml run --rm django pytest
