name: Django Testing Workflow

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop


jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Install flake8
      - run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Linting with flake8
      - run: flake8

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: run django pytest
        run: docker-compose -f local.yml run --rm django pytest
